### ISSUE TITLE
How to change help text?

### ISSUE THREAD

**Issue by tssajo** [alecthomas/kingpin#46]
This is more like a question (but maybe a feature request as well).

I am new to Go and very new to Kingpin. I'm about to re-create a [simple](https://github.com/alecthomas/kingpin#simple-example) CLI app in Go which I originally written some time ago in Node.js. (I do not need subcommands for my simple CLI app.) I'm progressing well.
However there are a few customization I would like to make to Kingpin. These are:

1. I prefer to have `-v, --version` with the text `Version information` instead of `--version` with the text `Show application version.`

2. I prefer to have `-h, --help` with the text `Display help and usage details` instead of `--help` with the text `Show help (also see --help-long and --help-man).` I don't need `--help-long` and `--help-man` at all, I just need `-h, --help` with customized description.

So the first one above I managed to solve by replacing
```
  kingpin.Version("0.0.1")
```
to this:
```
  kingpin.Flag("version", "Version information").Short('v').Action(func (*kingpin.ParseContext) error {
    fmt.Println("0.0.1")
    os.Exit(0)
    return nil
  }).Bool()
```

This works perfectly the way I want. I can now use the `-v` flag or `--version` flag and both print out the version info. (Note: The solution to this was not documented at all, I managed to come up with this solution by investigating the source code of Kingpin.)

But the second one (changing `--help` to `-h, --help` and its description) I cannot figure out.

Is there any way I can customize the default help flag? Especially in a simple CLI app (an app with no subcommands)?

Please let me know,

Thanks!

**Comment by alecthomas** [comment]
Hi,

Alas, there is no way to do what you want with the `--help` flag, and I doubt I will add it unless there's a compelling reason. The help flag is actually heavily special cased so that it works in basically all situations, meaning it is effectively a builtin. It's like this because in Kingpin v1 it was basically just a normal flag, but in certain situations (like invalid flags prior to the help flag) it became impossible to show the help correctly. By special casing it, it always works and always shows you help with as much information as you can.

As for `--help-long` I'm going to attempt to make that optional, as it is only useful if you have subcommands.

Alec

**Comment by cwaltken-edrans** [comment]
Hi @alecthomas, I just ran into the same thing.
You can easily a shorthand to the help flag, but you don't allow for a change of the help flags text? I think the default appeals more to a developer using kingpin then an end user. Why would i show them the flag to generate a man-page or a long-help if there is no difference?
```go
app.HelpFlag.Help("My custom text").Short('h')
```
would be awesome in my opinion...

**Comment by alecthomas** [comment]
I'm not sure what you're referring to... do you mean you'd like to see some longer text for flags, in addition to the flag help? eg. `kingpin.Flag("flag", "My flag help.").Help("My longer description of the flag")`?

**Comment by tssajo** [comment]
@alecthomas He "would like to see" what I wanted to be able to do two years ago:
We would like to be able to get rid of the awful help description which currently looks like this:
`--help             Show context-sensitive help (also try --help-long and --help-man).`
Especially, since we DO NOT HAVE any subcommands in our little apps!
We do not want to show this part to our users at all: "also try --help-long and --help-man", because we do not want that advanced crap. ;)
I considered forking your project just to be able to do this. But what's the point? Probably the best thing is abandoning the package because it is too large with too many unneeded features anyway. It makes a Go command line program gigabytes bigger. IMO, it's better to avoid it completely.

**Comment by alecthomas** [comment]
@tssajo It may be that your first language is not English, but you're coming off as entitled and rude. Please feel free to not use Kingpin if it doesn't meet your needs.

@cwaltken-edrans This is fixed in v3-unstable. The help text for `--help` is now `Show context-sensitive help.`.

**Comment by cwaltken-edrans** [comment]
@alecthomas what i meant is that it would be nice to be able to customize the text for the help flag freely. I think it's a little rigid to not allow for the user of your library to change that text to their needs.

**Comment by hsson** [comment]
I found that a simple way to get rid of the annoying help text showing `--help-long` and `--help-man` without changing any package code, is to simply do:
```go
func main() {
    app.HelpFlag.Hidden()
    ...
```
in the start of your own main function, where `app` in this case is your application created from `kingpin.New()`. This hides the `--help` flag in the help output, but this is not a big issue, as the `help` command is still shown to guide users.

**Comment by cwaltken-edrans** [comment]
Okay, thanks for the hint, but disabling the flag from the documentation
won't work for my use-case.
